a = float(input("Enter the element"))
b = float(input("Enter the element"))
print("addition is",a+b)
print("subtraction is", a-b)
print('division is',a/b)
print('multiplication is',a*b)
print('Exponent is a to b',a**b)
print('Exponent is b to a',b**a)
print('floor division is',a//b,'a//b')