a= int(input("Enter the value of a ")) 
b = int(input("Enter the value of b "))
c= int(input("Enter the value of c "))
d= int(input("Enter the value of d "))
print("a==b and c==d",(a==b and c==d))
print("a==b or c==d",(a==b or c==d))
print("not(a==b and c==d)",(not(a==b and c==d)))