import math
x = 2
y = -2
print("Ceil of x",math.ceil(x))
print("floor of x",math.floor(x))
print("copy sign of y in x",math.copysign(x,y))
print("absolute of y",math.fabs(y))
print("factorial of x",math.factorial(int(x)))
print("modulo of x and y",math.fmod(x,y))
print("is finite",math.isfinite(x))
print("is infinite",math.isinf(x))
print("is nan",math.isnan(x))
print("modf",math.modf(x))
print("trunc",math.trunc(x))
print("exp",math.exp(x))
print("exp2",math.exp2(x))
print("expm1",math.expm1(x))
print("loge",math.log(x))
print("log2",math.log2(x))
print("log10",math.log10(x))
print("log1p",math.log1p(x))
print("pow",math.pow(x,y))
print("sqrt",math.sqrt(x))